export * from './Header/Header';
export * from './MovieInfo/MovieInfo';
export * from './GenreBadge/GenreBadge';
export * from './UserInfo/UsreInfo';
export * from './MoviesList/MovieList';
export * from './MoviesListCard/MovieListCard';
export * from './PosterPreview/PosterPreview';
export * from './StarsRating/StarsRating';
export * from './MoviesInfo/MoviesInfo'